apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: horizon-sdv
  namespace: argocd
spec:
  description: Horizon SDV
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: horizon-sdv
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: horizon-sdv
  source:
    repoURL: https://github.com/AGBG-ASG/acn-horizon-sdv
    targetRevision: main
    path: gitops/env/dev/horizon-sdv-stage2
  destination:
    server: https://kubernetes.default.svc
  revisionHistoryLimit: 1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - Force=true
    automated:
      prune: true
      selfHeal: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
