external-secrets-chart:
  namespaceOverride: external-secrets
  extraObjects:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd

    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: argocd-sa
        namespace: argocd
        annotations:
          iam.gke.io/gcp-service-account: gke-argocd-sa@sdva-2108202401.iam.gserviceaccount.com

    - apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-github-agbg
        namespace: argocd
        labels:
          argocd.argoproj.io/secret-type: repository
      stringData:
        url: https://github.com/AGBG-ASG/acn-horizon-sdv
        type: git

    - apiVersion: external-secrets.io/v1beta1
      kind: SecretStore
      metadata:
        name: argocd-secret-store
        namespace: argocd
      spec:
        provider:
          gcpsm:
            projectID: "sdva-2108202401"
            auth:
              workloadIdentity:
                clusterLocation: europe-west1
                clusterName: sdv-cluster
                serviceAccountRef:
                  name: argocd-sa

    - apiVersion: external-secrets.io/v1beta1
      kind: ExternalSecret
      metadata:
        name: argocd-github-agbg
        namespace: argocd
      spec:
        refreshInterval: 10s
        secretStoreRef:
          kind: SecretStore
          name: argocd-secret-store
        target:
          name: argocd-github-agbg
          creationPolicy: Merge
        data:
          - secretKey: githubAppID
            remoteRef:
              key: githubAppID
          - secretKey: githubAppInstallationID
            remoteRef:
              key: githubAppInstallationID
          - secretKey: githubAppPrivateKey
            remoteRef:
              key: githubAppPrivateKey

argocd-chart:
  namespaceOverride: argocd
  configs:
    secret:
      argocdServerAdminPassword: "$2a$10$KF0ixwgtzCMyE0rrQLNDmOHVhK5e9/UJoGphL6oxmdx8vbJHcov7K"

  extraObjects:
    - apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: horizon-sdv
        namespace: argocd
      spec:
        description: Horizon SDV
        sourceRepos:
          - "*"
        destinations:
          - namespace: "*"
            server: https://kubernetes.default.svc
        clusterResourceWhitelist:
          - group: "*"
            kind: "*"
        namespaceResourceWhitelist:
          - group: "*"
            kind: "*"

    - apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: horizon-sdv
        namespace: argocd
        annotations:
          argocd.argoproj.io/manifest-generate-paths: .
      spec:
        project: horizon-sdv
        source:
          repoURL: https://github.com/AGBG-ASG/acn-horizon-sdv
          targetRevision: main
          path: gitops/env/dev/horizon-sdv-stage2
        destination:
          server: https://kubernetes.default.svc
        revisionHistoryLimit: 1
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
            - Replace=true
            - Force=true
          automated:
            prune: true
            selfHeal: false
          retry:
            limit: 5
            backoff:
              duration: 5s
              maxDuration: 3m0s
              factor: 2
