argocd-chart:
  namespaceOverride: argocd
  configs:
    secret:
      argocdServerAdminPassword: "$2a$10$KF0ixwgtzCMyE0rrQLNDmOHVhK5e9/UJoGphL6oxmdx8vbJHcov7K"
  extraObjects:
    - apiVersion: argoproj.io/v1alpha1
      kind: AppProject
      metadata:
        name: horizon-sdv
        namespace: argocd
      spec:
        description: Horizon SDV
        sourceRepos:
        - '*'
        destinations:
        - namespace: '*'
          server: https://kubernetes.default.svc
        clusterResourceWhitelist:
        - group: '*'
          kind: '*'
        namespaceResourceWhitelist:
        - group: '*'
          kind: '*'

external-secrets-chart:
   namespaceOverride: external-secrets
