apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: mtk-connect-route
  namespace: mtk-connect
  labels:
    gateway: gke-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  parentRefs:
    - kind: Gateway
      name: gke-gateway
      namespace: gke-gateway
      sectionName: https
  hostnames:
    - {{ .Values.config.domain }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mtk-connect/devices/ws
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"
      backendRefs:
        - name: mtk-connect-websockets
          port: 8086
    - matches:
        - path:
            type: PathPrefix
            value: /mtk-connect/ws
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/ws"
      backendRefs:
        - name: mtk-connect-wamprouter
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /mtk-connect
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"
      backendRefs:
        - name: mtk-connect-router
          port: 8081
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: mtk-connect-router-healthcheck
  namespace: mtk-connect
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: TCP
      tcpHealthCheck:
        port: 8081
  targetRef:
    group: ""
    kind: Service
    name: mtk-connect-router
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: mtk-connect-wamprouter-healthcheck
  namespace: mtk-connect
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: TCP
      tcpHealthCheck:
        port: 8080
  targetRef:
    group: ""
    kind: Service
    name: mtk-connect-wamprouter
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: mtk-connect-websockets-healthcheck
  namespace: mtk-connect
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: TCP
      tcpHealthCheck:
        port: 8086
  targetRef:
    group: ""
    kind: Service
    name: mtk-connect-websockets
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: mtk-connect-wamprouter-backendpolicy
  namespace: mtk-connect
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  default:
    timeoutSec: 86400
  targetRef:
    group: ""
    kind: Service
    name: mtk-connect-wamprouter
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: mtk-connect-websockets-backendpolicy
  namespace: mtk-connect
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  default:
    timeoutSec: 86400
  targetRef:
    group: ""
    kind: Service
    name: mtk-connect-websockets
