apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: horizon-sdv
  source:
    chart: keycloakx
    repoURL: https://codecentric.github.io/helm-charts
    targetRevision: 2.5.1
    helm:
      values: |
        command:
          - "/opt/keycloak/bin/kc.sh"
          - "--verbose"
          - "start"
          - "--http-port=8080"
          - "--hostname-strict=false"
          - "--spi-events-listener-jboss-logging-success-level=info"
          - "--spi-events-listener-jboss-logging-error-level=warn"

        extraEnv: |
          - name: KEYCLOAK_ADMIN
            value: admin
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-initial-creds
                key: password
          - name: JAVA_OPTS_APPEND
            value: >-
              -XX:MaxRAMPercentage=50.0
              -Djgroups.dns.query=keycloak-keycloakx-headless

        dbchecker:
          enabled: true

        database:
          existingSecret: postgresql-initial-creds
          vendor: postgres
          port: 5432
          hostname: postgresql
          username: dbusername
          database: keycloak

        service:
          httpPort: 8080

        proxy:
          mode: xforwarded

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
