apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zookeeper
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: horizon-sdv
  source:
    chart: zookeeper
    repoURL:  https://charts.bitnami.com/bitnami
    targetRevision: 13.5.1
  destination:
    server: https://kubernetes.default.svc
    namespace: zookeeper
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
