kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: reclaimable-storage-class
  annotations:
    reclaimable-pv-releaser.kubernetes.io/controller-id: dynamic-reclaimable-pvc-controllers
    argocd.argoproj.io/sync-wave: "3"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: pd-standard
  csi.storage.k8s.io/fstype: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: reclaimable-storage-class-balanced
  annotations:
    reclaimable-pv-releaser.kubernetes.io/controller-id: dynamic-reclaimable-pvc-controllers
    argocd.argoproj.io/sync-wave: "3"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: ext4
