apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: jenkins-route
  namespace: jenkins
  labels:
    gateway: gke-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  parentRefs:
    - kind: Gateway
      name: gke-gateway
      namespace: gke-gateway
      sectionName: https
  hostnames:
  - dev.horizon-sdv.scpmtk.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /jenkins
    filters:
    - type: URLRewrite
      urlRewrite:
        hostname: dev.horizon-sdv.scpmtk.com
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /jenkins
    backendRefs:
    - name: jenkins
      port: 8080
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: jenkins-healthcheck
  namespace: jenkins
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /jenkins/login
  targetRef:
    group: ""
    kind: Service
    name: jenkins
