apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: gerrit-route
  namespace: gerrit
  labels:
    gateway: gke-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  parentRefs:
    - kind: Gateway
      name: gke-gateway
      namespace: gke-gateway
      sectionName: https
  hostnames:
    - dev.horizon-sdv.scpmtk.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            hostname: dev.horizon-sdv.scpmtk.com
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: gerrit-service
          port: 8080
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: gerrit-healthcheck
  namespace: gerrit
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /config/server/healthcheck~status
  targetRef:
    group: ""
    kind: Service
    name: gerrit-service
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: gerrit-backendpolicy
  namespace: gerrit
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  default:
    timeoutSec: 86400
  targetRef:
    group: ""
    kind: Service
    name: gerrit-service