apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-rwx
  annotations:
    argocd.argoproj.io/sync-wave: "3"
provisioner: filestore.csi.storage.gke.io
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  network: sdv-network
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gerrit-shared-git
  namespace: gerrit
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: standard-rwx
  volumeMode: Filesystem
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gerrit
  namespace: gerrit
  annotations:
    argocd.argoproj.io/sync-wave: "3"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gerrit
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gerrit
  annotations:
    argocd.argoproj.io/sync-wave: "3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gerrit
subjects:
  - kind: ServiceAccount
    name: gerrit
    namespace: gerrit
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gerrit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: horizon-sdv
  source:
    repoURL: https://github.com/AGBG-ASG/acn-horizon-sdv
    targetRevision: main
    path: gitops/env/dev/horizon-sdv-stage2/apps/gerrit
  destination:
    server: https://kubernetes.default.svc
    namespace: gerrit-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
