apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-sa
  namespace: keycloak
  annotations:
    iam.gke.io/gcp-service-account: gke-keycloak-sa@sdva-2108202401.iam.gserviceaccount.com
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-initial-creds
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-horizon-admin
  namespace: keycloak
  labels:
    jenkins.io/credentials-type: "usernamePassword"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  username: "horizon-admin"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: keycloak-secret-store
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    gcpsm:
      projectID: "sdva-2108202401"
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: sdv-cluster
          serviceAccountRef:
            name: keycloak-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-initial-secret
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: keycloak-secret-store
  target:
    name: keycloak-initial-creds
    creationPolicy: Merge
  data:
  - secretKey: password
    remoteRef:
      key: keycloakInitialPassword
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-horizon-admin-secret
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: keycloak-secret-store
  target:
    name: keycloak-horizon-admin
    creationPolicy: Merge
  data:
    - secretKey: password
      remoteRef:
        key: keycloakHorizonAdminPassword