apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtk-connect-sa
  namespace: mtk-connect
  annotations:
    iam.gke.io/gcp-service-account: gke-mtk-connect-sa@sdva-2108202401.iam.gserviceaccount.com
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mtk-connect-secret-store
  namespace: mtk-connect
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    gcpsm:
      projectID: "sdva-2108202401"
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: sdv-cluster
          serviceAccountRef:
            name: mtk-connect-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mtk-connect-mtkc-regcred-secret
  namespace: mtk-connect
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: mtk-connect-secret-store
  target:
    name: mtk-connect-mtkc-regcred
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .mysecret | toString }}` }}"
  data:
    - secretKey: mysecret
      remoteRef:
        key: mtkc-regcred
