apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtk-connect-writer-sa
  namespace: mtk-connect
  annotations:
    argocd.argoproj.io/sync-wave: "4"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mtk-connect-writer-role
  namespace: mtk-connect
  annotations:
    argocd.argoproj.io/sync-wave: "3"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mtk-connect-writer-rolebinding
  namespace: mtk-connect
  annotations:
    argocd.argoproj.io/sync-wave: "4"
subjects:
  - kind: ServiceAccount
    name: mtk-connect-writer-sa
roleRef:
  kind: Role
  name: mtk-connect-writer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mtk-connect-cluster-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: mtk-connect-writer-sa
    namespace: mtk-connect
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mtk-connect-post-job
  namespace: mtk-connect
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    argocd.argoproj.io/hook: Sync
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 120
  template:
    spec:
      serviceAccountName: mtk-connect-writer-sa
      containers:
        - name: mtk-connect-post-container
          env:
            - name: REGISTRY
              value: "mywizard-gold.scpmtk.com/mtkc/registry"
            - name: REGISTRY_CREDS
              valueFrom:
                secretKeyRef:
                  name: mtk-connect-mtkc-regcred
                  key: .dockerconfigjson
            - name: AGENT_VERSION
              value: "v1.6.0"
            - name: TUNNEL_VERSION
              value: "v1.6.0"
            - name: GUACD_VERSION
              value: "v1.6.0"
            - name: NAMESPACE
              value: "mtk-connect"
          image: europe-west1-docker.pkg.dev/sdva-2108202401/horizon-sdv-dev/mtk-connect-post:latest
      restartPolicy: Never
