apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtk-connect-sa
  namespace: mtk-connect
  annotations:
    iam.gke.io/gcp-service-account: gke-mtk-connect-sa@sdva-2108202401.iam.gserviceaccount.com
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mtk-connect-secret-store
  namespace: mtk-connect
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    gcpsm:
      projectID: "sdva-2108202401"
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: sdv-cluster
          serviceAccountRef:
            name: mtk-connect-sa
