apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: horizon-sdv
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.0.3
    helm:
      values: |
        global:
          postgresql:
            auth:
              username: dbusername
              database: keycloak
              existingSecret: postgresql-initial-creds
              secretKeys:
                adminPasswordKey: postgres-password
                userPasswordKey: password
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
