apiVersion: v1
kind: Secret
metadata:
  name: postgresql-initial-creds
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  password: dbpassword
  postgres-password: dbpassword
