name: tf-checkov

on:
  workflow_call:
    secrets:
      fetcher-key:
        required: false
        description: "Github App Private Key (Deprecated, use gh-app-key)"
      gh-app-id:
        required: false
        description: "Github App ID"
      gh-installation-id:
        required: false
        description: "Github Installation ID"
      gh-app-key:
        required: false
        description: "Github App Private Key"

    inputs:
      gh-app-id:
        required: false
        description: "Github App ID"
        type: number
      gh-installation-id:
        required: false
        description: "Github Installation ID"
        type: number
      directory:
        required: false
        description: "Terraform directory"
        default: "terraform"
        type: string
      log-level:
        required: false
        description: "Checkov log level"
        default: "INFO"
        type: string

jobs:
  checkov:
    runs-on: self-hosted
    name: checkov

    steps:

    - name: get Github App Key
      id: get-env
      shell: bash
      run: |

        if [[ "${{ secrets.gh-app-id }}" != '' && "${{ secrets.gh-installation-id }}" != '' ]]; then
          echo "GITHUB_APP_ID=${{ secrets.gh-app-id }}" >> $GITHUB_ENV;
          echo "GITHUB_APP_INSTALLATION_ID=${{ secrets.gh-installation-id }}" >> $GITHUB_ENV;
        elif [[ "${{ inputs.gh-app-id }}" != '0' && "${{ inputs.gh-installation-id }}" != '0' ]]; then
          echo "GITHUB_APP_ID=${{ inputs.gh-app-id }}" >> $GITHUB_ENV;
          echo "GITHUB_APP_INSTALLATION_ID=${{ inputs.gh-installation-id }}" >> $GITHUB_ENV;
        else
          echo "Missing Github App id and/or Github Installation ID"
          exit 1
        fi

        if [[ "${{ secrets.gh-app-key }}" != '' ]]; then
          echo "GITHUB_APP_PEM_FILE<<EOF" >> $GITHUB_ENV
          echo  "${{ secrets.gh-app-key }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        elif [[ "${{ secrets.fetcher-key }}" != '' ]]; then
          echo "GITHUB_APP_PEM_FILE<<EOF" >> $GITHUB_ENV
          echo  "${{ secrets.fetcher-key }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        else
          echo "Missing Github App Key"
          exit 1
        fi

    - name: Get Terraform fetcher GitHub App token
      uses: tibdex/github-app-token@v1
      id: get_github_app_token
      with:
        app_id: ${{ env.GITHUB_APP_ID }}
        # installation_id not needed IF the app is installed on this current repo
        installation_id: ${{ env.GITHUB_APP_INSTALLATION_ID }}
        private_key: ${{ env.GITHUB_APP_PEM_FILE }}

    - name: Checkout source code
      uses: actions/checkout@v4.1.1

    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@v12.2125.0
      with:
        directory: ${{ inputs.directory }}
        quiet: false # optional: display only failed checks
        soft_fail: true # optional: do not return an error code if there are failed checks
        framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
        download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
        log_level: ${{ inputs.log-level }} # optional: set log level. Default INFO
        output_file_path: reports/results.sarif
        github_pat: ${{steps.get_github_app_token.outputs.token}}
