name: used - Terraform lint

on:
  workflow_call:
    inputs:
      terraform-path:
        required: false
        default: "terraform"
        type: string
      version:
        required: false
        default: latest
        type: string

jobs:
  tflint:
    runs-on: self-hosted
    name: tflint
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4.1.1

    - name: Cache plugin dir
      uses: actions/cache@v4
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4.0.0
      with:
        tflint_version: ${{ inputs.version }}

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint --chdir ${{ inputs.terraform-path }} -f compact
