name: Terraform

on:
  push:
    paths:
      - "terraform/*"
    branches: ["env/sbx"]
  workflow_dispatch:

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    concurrency:
      group: terraform
    permissions:
      contents: "read"
      id-token: "write"
      pull-requests: "write"
    secrets:
      gh-app-key: "${{ secrets.GH_APP_KEY }}"
      gcp-sa: "${{ secrets.GCP_SA }}"
      wif-provider: "${{ secrets.WIF_PROVIDER }}"
      gh-app-id: ${{ secrets.GH_APP_ID }}
      gh-argocd-initial-password-bcrypt: ${{ secrets.ARGOCD_INITIAL_PASSWORD_BCRYPT }}
      gh-jenkins-initial-password: ${{ secrets.JENKINS_INITIAL_PASSWORD }}
      gh-keycloak-initial-password: ${{ secrets.KEYCLOAK_INITIAL_PASSWORD }}
      gh-gerrit-admin-initial-password: ${{ secrets.GERRIT_ADMIN_INITIAL_PASSWORD }}
      gh-gerrit-admin-private-key: ${{ secrets.GERRIT_ADMIN_PRIVATE_KEY }}
      gh-keycloak-horizon-admin-password: ${{ secrets.KEYCLOAK_HORIZON_ADMIN_PASSWORD }}
      gh-cuttlefish-vm-ssh-private-key: ${{ secrets.CUTTLEFISH_VM_SSH_PRIVATE_KEY }}
    with:
      terraform-version: 1.9.6
      environment: sbx
      directory: terraform/env
