name: used - Terraform fmt

on:
  workflow_call:
    inputs:
      terraform-path:
        required: false
        default: "terraform"
        type: string
      terraform-version:
        required: false
        default: latest
        type: string
      continue-on-error:
        required: false
        default: false
        type: boolean

jobs:
  terraformfmt:
    name: terraform fmt
    runs-on: self-hosted
    steps:

    - name: Checkout source code
      uses: actions/checkout@v4.1.1

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: terraform fmt
      working-directory: ${{ inputs.terraform-path }}/
      run: terraform fmt -check -recursive
      continue-on-error: ${{ inputs.continue-on-error }}