name: Terraform Workflow
run-name: Running Terraform Workflow by @${{ github.actor }}

on:
  push:
    branches:
     - main
     - 'feature/**'
     - 'release/**'
  pull_request:
    branches:
      - main

jobs:
  generate-matrix:
    name: Generate job matrices
    runs-on: ubuntu-latest
    # don't forget to declare outputs here!
    outputs:
      matrix-infrastructure: ${{ steps.neo-infrastructure.outputs.matrix }}
    steps:
      - name: Generate matrix | Infrastructure
        id: neo-infrastructure
        uses: hellofresh/action-changed-files@v3
        with:
            pattern: terraform/env/(?P<environment>[^/]+)

  terraform:
    needs: [ generate-matrix ] # don't forget this!
    permissions:
     contents: 'read'
     id-token: 'write'
     pull-requests: 'write'
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix-infrastructure) }}
    if: ${{ fromJson(needs.generate-matrix.outputs.matrix-infrastructure).include[0] }} # skip if the matrix is empty!
    uses: ./.github/workflows/terraform_dynamic_envs.yaml
    secrets:
      gcp-sa: "${{ secrets.GCP_SA }}"
      wif-provider: "${{ secrets.WIF_PROVIDER }}"
    with:
      path: terraform/env/${{ matrix.environment }}
      environment: ${{ matrix.environment }}
      terraform-version: 1.9.6