name: Terraform Validate

on:
  workflow_call:
    secrets:
      fetcher-key:
        required: false
        description: "Github App Private Key (Deprecated, use gh-app-key)"
      gh-app-id:
        required: false
        description: "Github App ID"
      gh-installation-id:
        required: false
        description: "Github Installation ID"
      gh-app-key:
        required: false
        description: "Github App Private Key"

    inputs:
      gh-app-id:
        required: false
        description: "Github App ID"
        type: number
      gh-installation-id:
        required: false
        description: "Github Installation ID"
        type: number
      terraform-path:
        required: false
        default: "terraform"
        type: string
      terraform-version:
        required: false
        default: latest
        type: string
      continue-on-error:
        required: false
        default: false
        type: boolean

jobs:
  validate:
    runs-on: self-hosted
    name: validate

    steps:

    - name: get Github App Key
      id: get-env
      shell: bash
      run: |

        if [[ "${{ secrets.gh-app-id }}" != '' && "${{ secrets.gh-installation-id }}" != '' ]]; then
          echo "GITHUB_APP_ID=${{ secrets.gh-app-id }}" >> $GITHUB_ENV;
          echo "GITHUB_APP_INSTALLATION_ID=${{ secrets.gh-installation-id }}" >> $GITHUB_ENV;
        elif [[ "${{ inputs.gh-app-id }}" != '0' && "${{ inputs.gh-installation-id }}" != '0' ]]; then
          echo "GITHUB_APP_ID=${{ inputs.gh-app-id }}" >> $GITHUB_ENV;
          echo "GITHUB_APP_INSTALLATION_ID=${{ inputs.gh-installation-id }}" >> $GITHUB_ENV;
        else
          echo "Missing Github App id and/or Github Installation ID"
          exit 1
        fi

        if [[ "${{ secrets.gh-app-key }}" != '' ]]; then
          echo "GITHUB_APP_PEM_FILE<<EOF" >> $GITHUB_ENV
          echo  "${{ secrets.gh-app-key }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        elif [[ "${{ secrets.fetcher-key }}" != '' ]]; then
          echo "GITHUB_APP_PEM_FILE<<EOF" >> $GITHUB_ENV
          echo  "${{ secrets.fetcher-key }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        else
          echo "Missing Github App Key"
          exit 1
        fi

    - name: Get Terraform fetcher GitHub App token
      uses: tibdex/github-app-token@v1
      id: get_github_app_token
      with: 
        app_id: ${{ env.GITHUB_APP_ID }}
        # installation_id not needed IF the app is installed on this current repo
        installation_id: ${{ env.GITHUB_APP_INSTALLATION_ID }}
        private_key: ${{ env.GITHUB_APP_PEM_FILE }}

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Checkout source code
      uses: actions/checkout@v4.1.1

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Terraform init
      working-directory: ${{ inputs.terraform-path }}/
      run: |
        git config --global url."https://x-access-token:${{steps.get_github_app_token.outputs.token}}@github.com".insteadOf https://github.com
        terraform init -input=false

    - name: Terraform validate
      working-directory: ${{ inputs.terraform-path }}/
      run: terraform validate
      continue-on-error: ${{ inputs.continue-on-error }}
