name: tf-module

on:
  workflow_call:
    secrets:
      gh-app-id:
        required: false
        description: "Github App ID"
      gh-installation-id:
        required: false
        description: "Github Installation ID"
      gh-app-key:
        required: true
        description: "Github App Private Key"

    inputs:
      gh-app-id:
        required: false
        description: "Github App ID"
        type: number
      gh-installation-id:
        required: false
        description: "Github Installation ID"
        type: number
      terraform-version:
        required: false
        default: latest
        type: string
      path:
        required: false
        default: "."
        type: string

jobs:

  validate:
    uses: ./.github/workflows/terraform_validate.yaml
    secrets:
      gh-app-key: "${{ secrets.gh-app-key }}"
    with:
      gh-app-id: ${{ inputs.gh-app-id }}
      gh-installation-id: ${{ inputs.gh-installation-id }}
      terraform-path: ${{ inputs.path }}

  tflint:
    uses: ./.github/workflows/tflint.yaml
    with:
      terraform-path: ${{ inputs.path }}
  
  checkov:
    uses: ./.github/workflows/checkov.yaml
    secrets:
      gh-app-key: "${{ secrets.gh-app-key }}"
    with:
      gh-app-id: ${{ inputs.gh-app-id }}
      gh-installation-id: ${{ inputs.gh-installation-id }}
      directory: ${{ inputs.path }}


  update-repo:
    runs-on: self-hosted
    needs: [tflint, checkov, validate]

    steps:
    - name: set environment variables
      id: set-vars
      shell: bash
      run: |

        if [[ "${{ secrets.gh-app-id }}" != '' && "${{ secrets.gh-installation-id }}" != '' ]]; then
          echo "GITHUB_APP_ID=${{ secrets.gh-app-id }}" >> $GITHUB_ENV;
          echo "GITHUB_APP_INSTALLATION_ID=${{ secrets.gh-installation-id }}" >> $GITHUB_ENV;
        elif [[ "${{ inputs.gh-app-id }}" != '0' && "${{ inputs.gh-installation-id }}" != '0' ]]; then
          echo "GITHUB_APP_ID=${{ inputs.gh-app-id }}" >> $GITHUB_ENV;
          echo "GITHUB_APP_INSTALLATION_ID=${{ inputs.gh-installation-id }}" >> $GITHUB_ENV;
        else 
          echo "Missing Github App id and/or Github Installation ID"
          exit 1
        fi
        
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: Setup terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Get Terraform fetcher GitHub App token
      uses: tibdex/github-app-token@v1
      id: app_token
      with: 
        app_id: ${{ env.GITHUB_APP_ID }}
        installation_id: ${{ env.GITHUB_APP_INSTALLATION_ID}}
        private_key: ${{ secrets.gh-app-key }}

    - name: Download Terraform Module Template Files
      run: |
        curl https://raw.githubusercontent.com/AGBG-ASG/terraform-module-template/main/.terraform-docs.yml -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" -o .terraform-docs.yml
        curl https://raw.githubusercontent.com/AGBG-ASG/terraform-module-template/main/LICENSE -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" -o LICENSE
        curl https://raw.githubusercontent.com/AGBG-ASG/terraform-module-template/main/.gitignore -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" -o .gitignore
        curl https://raw.githubusercontent.com/AGBG-ASG/terraform-module-template/main/CODEOWNERS -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" -o CODEOWNERS
   
    - name: Render terraform docs inside the README.md
      run: |
        curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
        tar -xzf terraform-docs.tar.gz terraform-docs
        chmod +x terraform-docs
        ./terraform-docs -c .terraform-docs.yml .
        rm terraform-docs terraform-docs.tar.gz
    
    - name: terraform fmt
      working-directory: ${{ inputs.path }}/
      run: terraform fmt -recursive
      continue-on-error: true

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update documentation"
        commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
