name: Terraform Root Workflow

on:
  push:
    paths:
      - 'terraform/env/dev/*'
      - 'terraform/modules/*'
    branches: [
      "feature/*"
      ]
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:

  get-env:
    name: Get environment
    runs-on: self-hosted
    env:
      TERRAFORM_DIR: ${{ vars.TERRAFORM_DIR }}
    steps:
    - name: get environment
      id: get-env
      shell: bash
      run: |
        echo "${{ env.TERRAFORM_DIR }}"

  checkov:
    uses: ./.github/workflows/checkov.yaml
    secrets:
      fetcher-key: "${{ secrets.GH_APP_KEY }}"
      gh-app-id: ${{ secrets.GH_APP_ID }}
      gh-installation-id: ${{ secrets.GH_INSTALLATION_ID }}
    with:
      directory: terraform

  tflint:
    uses: ./.github/workflows/tflint.yaml
    with:
      terraform-path: terraform

  trivy:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/trivy_secret_scan.yaml

  terraformfmt:
    uses: ./.github/workflows/terraform_fmt.yaml
    with:
      terraform-path: terraform
      terraform-version: 1.7.2

  terraform:
    needs: [terraformfmt,tflint,checkov,trivy]
    uses: ./.github/workflows/terraform.yaml
    concurrency:
      group: terraform
    permissions:
     contents: 'read'
     id-token: 'write'
     pull-requests: 'write'
    secrets:
      gh-app-key: "${{ secrets.GH_APP_KEY }}"
      gcp-sa: "${{ secrets.GCP_SA }}"
      wif-provider: "${{ secrets.WIF_PROVIDER }}"
      gh-app-id: ${{ secrets.GH_APP_ID }}
      gh-installation-id: ${{ secrets.GH_INSTALLATION_ID }}
    with:
      terraform-version: 1.7.2